import 'package:mysql_client/mysql_client.dart';
import 'connection.dart';

//Class whose purpose is to insert a record into the database
class Insert extends APIConnector {
  Insert();

  //Primary function which executes the record insertion. Take in a list of things to insert, the table to insert them into, and whether the first column is being used, or if it's autogenerated.
  void insertInDatabase(
      List<String> toInsert, String table, bool readFirst) async {
    //Begin statement construction
    String statement = "INSERT INTO $table";
    //Initialize columns
    List<String> columns;
    //If the first column (sometimes a generated ID) is being used, then get columns including it
    if (readFirst) {
      columns = await getColumns(table);
    }
    //Otherwise, if the column is autogenerated, just grab the subequent columns
    else {
      columns = await getColumnsIgnoreFirst(table);
    }
    //Check to see if the argument is valud
    if (isValidArgument(columns, toInsert)) {
      //Update the SQL statement
      statement += constructInsertion(columns, toInsert);
    }
    //Open the connection
    MySQLConnection conn = await openConnection();
    //Execute the SQL statement
    await conn.execute(statement);
    //Close the connection
    conn.close();
  }

  //Check to ensure that the amount of columns in the table that have been selected is equivalent to the parameter list
  bool isValidArgument(List<String> cols, List<String> inserting) {
    //Check to see if the lengths are the same
    if (cols.length == inserting.length) {
      return true;
    }
    return false;
  }

  //Helper function to construct the insertion query
  String constructInsertion(List<String> cols, List<String> params) {
    return (" ${buildQuery(cols, true)} VALUES ${buildQuery(params, false)}");
  }

  //Build the query
  String buildQuery(List<String> paramList, bool cols) {
    String query = "(";
    for (String param in paramList) {
      //If adding a column, don't incude apostrophes indicating a value
      if (cols) {
        query += ("$param, ");
      } else {
        query += ("'$param', ");
      }
    }
    //Shorten the query and remove the ','
    query = query.substring(0, query.length - 2);
    //Close the statement
    query += ")";
    //Return the query
    return query;
  }
}
